"""Canonical schema package."""
from schema.canonical import (
    CanonicalStatus,
    CanonicalTestResult,
    ErrorType,
    EvidenceType,
    ToolInfo,
    SuiteInfo,
    Summary,
    ToolStats,
    TestCaseResult,
    QualitySignal,
    QualityIssue,
    NormalizedError,
    EvidenceFile,
    QualityEvaluation,
    NormalizeContext,
    RawResultSource,
    VALID_STATUSES,
)
